on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
      # sam build 
      - name: build
        run: sam build --use-container

# Run Unit tests- Specify unit tests here 

# sam deploy
      - name: deploy
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name lamba-resume --s3-bucket aws-sam-cli-managed-prod-pipeline-artifactsbucket-jf68tabmu6xf --capabilities CAPABILITY_IAM --region us-east-1